POST http://localhost:3333/videos
Content-Type: application/json
 
{
    "title": "Video de teste",
    "description": "Descrição do video de teste",
    "url": "https://www.youtube.com/watch?v=GQp1zzTwrIg"
}