POST http://localhost:3333/videos
Content-Type: application/json
 
{
    "title": "Video node",
    "description": "Descrição do video de node",
    "url": "https://www.youtube.com/watch?v=GQp1zzTwrIg"
}

###


GET  http://localhost:3333/videos?source=node

###

PUT http://localhost:3333/videos/9ae44a8a-1eef-40bd-9276-f9a66e87b781
Content-Type: application/json

{
    "title": "Video de teste 1 atualizado",
    "description": "Descrição do video de teste atualizado",
    "url": "https://www.youtube.com/watch?v=GQp1zzTwrIg"
}

###

DELETE http://localhost:3333/videos/13857a2b-2ed9-4b48-85c5-6e5407e412b9