POST https://nodejs-e-api-rest-basico.onrender.com
Content-Type: application/json
 
{
    "title": "Video teste deploy",
    "description": "Descrição do video de node",
    "url": "https://www.youtube.com/watch?v=GQp1zzTwrIg"
}

###


GET  https://nodejs-e-api-rest-basico.onrender.com

###

PUT https://nodejs-e-api-rest-basico.onrender.com
Content-Type: application/json

{
    "title": "Video de teste 1 atualizado",
    "description": "Descrição do video de teste atualizado",
    "url": "https://www.youtube.com/watch?v=GQp1zzTwrIg"
}

###

DELETE https://nodejs-e-api-rest-basico.onrender.com